- name: Remove old git repo
  file:
    state: absent
    path: "{{ account_code_dir }}/"

- name: Remove old app repo
  file:
    state: absent
    path: "{{ account_app_dir }}"

- name: Create account app folder
  file:
    path: "{{ account_app_dir }}"
    state: directory
    owner: "{{ account_user }}"
    group: "{{ account_user }}"

- name: Checkout account repo into {{ account_code_dir }}
  git:
    dest: "{{ account_code_dir }}"
    repo: "{{ account_repo }}"
    version: "{{ ACCOUNT_VERSION }}"
    accept_hostkey: yes
  become_user: "{{ account_user }}"
  register: account_checkout


# Use apt to install nodeenv, so we can use nodeenv to install nodejs
- name: install nodenv by using apt
  apt:
    name: nodeenv
  tags:
    - install
    - install:system-requirements

# Install node
- name: install nodejs
  shell: "nodeenv {{ account_nodeenv_dir }} --node={{ ACCOUNT_NODE_VERSION }} --prebuilt --force"
  become_user: "{{ account_user }}"
  environment: "{{ account_env_vars }}"
  tags:
    - install
    - install:system-requirements

# Set the npm registry
# This needs to be done as root since npm is weird about
# chown - https://github.com/npm/npm/issues/3565
- name: Set the npm registry
  shell: "{{ account_nodeenv_bin }}/npm config set registry '{{ COMMON_NPM_MIRROR_URL }}'"
  args:
    creates: "{{ account_code_dir }}/.npmrc"
  environment: "{{ account_env_vars }}"
  become_user: "{{ account_user }}"
  tags:
    - install
    - install:app-requirements

#we need to do this so that npm can find a node install to use to build node-sass
- name: prepend node path
  shell: "{{ account_nodeenv_bin }}/npm config set scripts-prepend-node-path true"
  environment: "{{ account_env_vars }}"
  become_user: "{{ account_user }}"
  tags:
    - install
    - install:app-requirements

#install with the shell command instead of the ansible npm module so we don't accidentally re-write package.json
#The version of ansible we are using also does not make use of "--unsafe-perm", which we need for node-sass
- name: install node dependencies
  shell: "sudo {{ account_nodeenv_bin }}/node {{ account_nodeenv_bin }}/npm i --unsafe-perm"
  args:
    chdir: "{{ account_code_dir }}"
  environment: "{{ account_env_vars }}"
  become: true
  become_method: sudo
  tags:
    - install
    - install:app-requirements

#install with the shell command instead of the ansible npm module so we don't accidentally re-write package.json
- name: run account build
  shell: "npm run build"
  args:
    chdir: "{{ account_code_dir }}"
  environment: "{{ account_env_vars }}"
  become_user: "{{ account_user }}"
  tags:
    - install
    - install:app-requirements
