- name: Deploy account MFE Frontend
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'account'
    ACCOUNT_ENABLED: True
    ACCOUNT_SANDBOX_BUILD: False
  roles:
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
    - role: nginx
      nginx_sites:
      - account
      ACCOUNT_NGINX_PORT: 8978
    - account
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
